spring:
  config:
    activate:
      on-profile: localDynamo
    import: "optional:configserver:http://localhost:9500/"
  cloud:
    config:
      name: nosql
      profile: dynamo

encrypt:
  key: EjelT7fFw6T4LHQEuwtU

grpc:
  shop-query: localhost
  shop-search: localhost